form Box1HouseOwning {
hasSoldHouse: "Did you sell a house in 2010?" boolean (2)
hasSoldHouse2: "Did you sell a house in 2010?" boolean (2)
}
form Box1HouseOwning {
hasSoldHouse: "Did you sell a house in 2010?" boolean (2)
}
form Box1HouseOwning {
hasSoldHouse: "Did you sell a house in 2010?" boolean (2)
hasSoldHouse2: "Did you sell a house in 2010?" boolean (2)
}
form Box1HouseOwning {
hasSoldHouse: "Did you sell a house in 2010?" boolean (2)
}
